services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/6s
      - NODE_ENV=production
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:8.0.11
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=6s
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge